name: portfolio_bonas
description: This is Bonas' Portfolio. Done with charm by Jael-dev.

# Prevents accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# The different dependencies in the project

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_localization: ^0.1.10
  flutter_riverpod: ^2.3.0
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  algolia: ^1.1.2
  algolia_helper_flutter: ^0.2.3
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  # Assets from the images directory of the application.
  assets:
    - assets/images/
    - assets/google_fonts/

  
  # Fonts used in the application from the assets directory.
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/google_fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/google_fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/google_fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/google_fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/google_fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
